// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"
)

const getURL = `-- name: GetURL :one
SELECT URL FROM urls WHERE shortURL = $1
`

func (q *Queries) GetURL(ctx context.Context, shorturl string) (string, error) {
	row := q.db.QueryRow(ctx, getURL, shorturl)
	var url string
	err := row.Scan(&url)
	return url, err
}

const saveURL = `-- name: SaveURL :one
INSERT INTO urls (URL, shortURL) VALUES ($1, $2) RETURNING shortURL
`

type SaveURLParams struct {
	Url      string
	Shorturl string
}

func (q *Queries) SaveURL(ctx context.Context, arg SaveURLParams) (string, error) {
	row := q.db.QueryRow(ctx, saveURL, arg.Url, arg.Shorturl)
	var shorturl string
	err := row.Scan(&shorturl)
	return shorturl, err
}
